webapp/webapp/category/models.py
from webapp.model import db

class Category(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    category = db.Column(db.String(50), index=True, nullable=True)

    def __repr__(self) -> str:
        return '{}'.format(self.category)

webapp/webapp/user/models.py
from flask_login import UserMixin
from sqlalchemy import ForeignKey

from webapp.model import db

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(50), index=True, nullable=True)
    last_name = db.Column(db.String(50), index=True, nullable=True)
    email = db.Column(db.String(100), unique=True)

    def __repr__(self) -> str:
        return '<User {}>'.format(self.first_name)


class User_Choice(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, ForeignKey(User.id), nullable=True)
    category_id = db.Column(db.Integer, nullable=True)
    upload = db.Column(db.DateTime, nullable=True)

    def __repr__(self) -> str:
        return '<ID {}>'.format(self.id)

webapp/webapp/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired

class UserForm(FlaskForm):
    first_name = StringField('Имя', validators=[DataRequired()], render_kw={'class': 'form-control'})
    last_name = StringField('Фамилия', validators=[DataRequired()], render_kw={'class': 'form-control'})
    submit = SubmitField('Отправить', render_kw={'class': 'btn btn-primary'})

webapp/webapp/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Email

class UserForm(FlaskForm):
    first_name = StringField('Имя', validators=[DataRequired()], render_kw={'class': 'form-control'})
    last_name = StringField('Фамилия', validators=[DataRequired()], render_kw={'class': 'form-control'})
    email = StringField('Email', validators=[DataRequired(), Email()], render_kw={'class': 'form-control'})
    submit = SubmitField('Отправить', render_kw={'class': 'btn btn-primary'})

webapp/webapp/__init__.py
from flask import Flask
from flask_login import LoginManager

from webapp.model import db
from webapp.user.models import User

from webapp.user.views import blueprint as user_blueprint
from webapp.category.views import blueprint as category_blueprint

def create_app():
    app = Flask(__name__)
    app.config.from_pyfile('config.py')
    db.init_app(app)

    with app.app_context():
        db.create_all()

    login_manager = LoginManager()
    login_manager.init_app(app)
    login_manager.login_view = 'user.login'
    app.register_blueprint(user_blueprint)
    app.register_blueprint(category_blueprint)


    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(user_id)

    return app

webapp/webapp/category/views.py
from flask import Blueprint, render_template, flash, redirect, url_for, request
from flask_login import current_user, logout_user
from sqlalchemy.exc import ProgrammingError

from webapp.db_functions import create_user_choice
from webapp.category.models import Category

blueprint = Blueprint('category', __name__)

@blueprint.route('/category', methods=['GET', 'POST'])
def index():
    page_title = 'Бот покупок'
    category_list = Category.query.all()
    if "marker" in request.form:
        select_category = request.form.getlist("category")
        try:
            create_user_choice(select_category, current_user.email)
            logout_user()
            flash('Ваш выбор сохранен.Вы можете вернуться к телеграм-боту.')
        except (ProgrammingError, AttributeError):
            flash('Сначала заполните форму входа.')
            return redirect(url_for('user.registration'))
    return render_template(
        'category/index.html', title=page_title, categories=category_list,
        )

webapp/webapp/user/views.py
from flask import Blueprint, render_template, url_for, flash, redirect
from flask_login import login_user


from sqlalchemy.exc import IntegrityError

from webapp.db_functions import create_user
from webapp.user.forms import UserForm
from webapp.user.models import User

blueprint = Blueprint('user', __name__)

@blueprint.route('/')
def registration():
    registration_form = UserForm()
    return render_template('user/registration.html', form=registration_form)

@blueprint.route('/process-registration', methods=['POST'])
def process_registration():
    form = UserForm()
    if form.validate_on_submit():
        first_name = form.first_name.data
        last_name = form.last_name.data
        email = form.email.data
        if User.query.filter(User.first_name == first_name, User.last_name == last_name, User.email == email).count():
            user = User.query.filter_by(email=email).first()
            login_user(user)
            return redirect(url_for('category.index'))
        else:
            try:
                create_user(first_name,last_name, email)
                user = User.query.filter_by(email=form.email.data).first()
                login_user(user)
            except IntegrityError:
                flash('Пользователь с таким email уже существует.')
                return redirect(url_for('user.registration'))
            return redirect(url_for('category.index'))
    flash('Введите корректную почту.')
    return redirect(url_for('user.registration'))

webapp/templates/index.html
<html lang="ru">
    <head>
         <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

        <title>{{ title }}</title>
    </head>
    <body>
        <div class="container">
            <h1><u>Категории</u></h1>
            <div class="row">
                <div class="col-12">
                </div>
                <style type="text/css"> 
                    button[name="confirm"] { 
                      border: none;
                      border-radius: 10px;
                      padding: 5px 25px;
                      background: #0466e6;
                      font-weight: bold;
                      color: white;
                    }
                  </style>
                  <button type="button" name="confirm">Подтвердить</button>
            </div>      
        </div>
        <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </body>
</html>

webapp/webapp/templates/base.html
<html lang="ru">
    <head>
         <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

        <title>{{ title }}</title>
    </head>
    <body>
        <div class="container">
        {% block content %}{% endblock %}
        </div>
        <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </body>
</html>

webapp/webapp/templates/category/index.html
{% extends "base.html" %}

{% block content %}
    <h1><u>Категории</u></h1>
    <div class="row">
        <div class="col-4">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                <div class="alert alert-warning" role="alert">
                    {% for message in messages %}
                        {{ message }}<br>
                    {% endfor %}
                </div>
                {% endif %}
            {% endwith %}    
            <form name="category" method="POST">
                {% for category in categories %}
                    <input class="form-check-input" type="checkbox" id={{loop.index}} name="category" value="{{ category }}">
                    <label for={{loop.index}}>{{ category }}</label><br>
                {% endfor %}
                <style type="text/css"> 
                    button[name="marker"] { 
                        border: none;
                        border-radius: 5px;
                        padding: 5px 25px;
                        background: #0475e6;
                        color: white;
                    }
                </style>
                <button type="submit" name="marker">Подтвердить</button>
            </form>
        </div>
    </div>
{% endblock %}

webapp/webapp/templates/user/registration.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        <div class="col-4">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                <div class="alert alert-warning" role="alert">
                    {% for message in messages %}
                        {{ message }}<br>
                    {% endfor %}
                </div>
                {% endif %}
            {% endwith %}
            <form action="{{ url_for('user.process_registration') }}" method="POST">
                {{ form.hidden_tag() }}
                <div class="form-group">
                    {{ form.first_name.label }}
                    {{ form.first_name() }}
                </div>
                <div class="form-group">
                    {{ form.last_name.label }}
                    {{ form.last_name() }}
                </div>
                <div class="form-group">
                    {{ form.email.label }}
                    {{ form.email() }}
                </div>
                {{ form.submit }}
            </form>
        </div>
    </div> 
{% endblock %}